[project]
name = "python-adk-weather-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "google-adk>=1.4.2",
    "ipykernel>=6.29.5",
    "ipython>=9.3.0",
    "litellm>=1.73.0",
]
